#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

enum error_code {
    NO_ERROR = 0,
    ERROR_OPENING_DB,
    ERROR_CREATING_TABLE_DB,
    ERROR_INSERT_DB,
    ERROR_UPDATE_DB,
    ERROR_DELETE_DB,
};

#endif // ERROR_HANDLING_H